// Copyright Epic Games, Inc. All Rights Reserved.
#pragma once

#include "NativeGameplayTags.h"

namespace MainGameplayTags
{
	PROJECTRWW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Damaged);
	PROJECTRWW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
	PROJECTRWW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_HPRegen);
	PROJECTRWW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_ManaRegen);
	PROJECTRWW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_HPRegenDelay);
	PROJECTRWW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_ManaCost);
	PROJECTRWW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_WeaponSkill);
	PROJECTRWW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_ClearOnDeath);
}
